zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
        - "9092:9092"
    links:
        - zookeeper    
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        #todo: figure out a way to stop using this hard-coded ip
        KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
        KAFKA_CREATE_TOPICS: "all:1:1"
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        #HOSTNAME_COMMAND: ifconfig docker0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'

kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
        - "9000:9000"
    links:
        - zookeeper
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "letmein"

